stages:
  - build
  - merge
  - release-prepare
  - release-upload
  - release-gitlab

variables:
  ACTIVE_ROS_DISTRO: "lyrical jazzy"

#
# Build LGDXRobot2 ROS 2
#

build-amd64:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
      when: never 
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_COMMIT_BRANCH !~ /\// && $CI_COMMIT_BRANCH !~ /cherry-pick/  
  image: docker:24.0.5-git
  tags:
    - saas-linux-small-amd64
  services:
    - docker:24.0.5-dind
  variables:
    ARCH: amd64
  before_script:
    - apk add zip
  script:
    - docker build -f Dockerfile -o . .
    - cd debs
    - zip -r lgdx_rplidar_c1-$ARCH.zip *
  artifacts:
    paths:
      - debs/lgdx_rplidar_c1-$ARCH.zip
    expire_in: 1 day

build-arm64:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
      when: never 
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_COMMIT_BRANCH !~ /\// && $CI_COMMIT_BRANCH !~ /cherry-pick/
  image: docker:24.0.5-git
  tags:
    - saas-linux-small-arm64
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    ARCH: arm64
  services:
    - name: docker:24.0.5-dind
      command: ["--mtu=1300"]
  before_script:
    - apk add zip
  script:
    - docker build -f Dockerfile -o . .
    - cd debs
    - zip -r lgdx_rplidar_c1-$ARCH.zip *
  artifacts:
    paths:
      - debs/lgdx_rplidar_c1-$ARCH.zip
    expire_in: 1 day

#
# Merge
#

merge:
  image: alpine:latest
  stage: merge
  rules:
    - if: $CI_COMMIT_TAG
      when: never 
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  
  before_script:
    - apk add python3
    - apk add curl
  script:
    - curl -L -s -o merge.py https://gitlab.com/lgdxrobotics/release-strategy-helpers/-/raw/main/merge.py?ref_type=heads
    - python merge.py
#
# Release
#

release-prepare:
  stage: release-prepare
  rules:
    - if: $CI_COMMIT_TAG
      when: never 
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH 
      when: manual
  image: alpine:latest
  script:
    - apk add libxml2-utils
    - echo "APP_VERSION=$(xmllint --xpath "//package/version/text()" lgdx_rplidar_c1/package.xml)" >> variables.env
  artifacts:
    reports:
      dotenv: variables.env
    expire_in: 1 day

release-gitlab:
  stage: release-gitlab
  image: alpine:latest
  rules:
    - if: $CI_COMMIT_TAG
      when: never 
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  needs:
    - job: release-prepare
      artifacts: true
  script:
    - apk add glab
  release:
    name : '$APP_VERSION'
    tag_name: '$APP_VERSION'
    description: '$APP_VERSION'
    ref: '$CI_COMMIT_SHA'

# Distro only

release-upload:
  stage: release-upload
  image: alpine:latest
  rules:
    - if: $CI_COMMIT_TAG
      when: never 
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_COMMIT_BRANCH !~ /\// && $CI_COMMIT_BRANCH !~ /cherry-pick/ && $CI_PIPELINE_SOURCE != "merge_request_event"
  needs:
    - job: build-amd64
      artifacts: true
    - job: build-arm64
      artifacts: true
  before_script:
    - apk add curl
  script:
    - cd debs
    - |
      curl --location --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
           --upload-file lgdx_rplidar_c1-amd64.zip \
           "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/lgdx_rplidar_c1/$CI_COMMIT_BRANCH/lgdx_rplidar_c1-amd64.zip"
    - |
      curl --location --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
           --upload-file lgdx_rplidar_c1-arm64.zip \
           "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/lgdx_rplidar_c1/$CI_COMMIT_BRANCH/lgdx_rplidar_c1-arm64.zip"
